version: '3.8'
services:
  api-gateway:
    build:
      context: ../services/PickAPod.Gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
      - "5001:5001" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - photo-service
      - user-service
      - favorites-service
      - logging-service

  photo-service:
    build:
      context: ../services/PickAPod.Photo
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  user-service:
    build:
      context: ../services/PickAPod.User
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  favorites-service:
    build:
      context: ../services/PickAPod.Favorite
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  logging-service:
    build:
      context: ../services/PickAPod.Logging
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
