apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
      - name: logging-service
        image: logging-service:latest
        ports:
        - containerPort: 5004
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  ports:
  - protocol: TCP
    port: 5001
  selector:
    app: logging-service
