apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      containers:
      - name: photo-service
        image: photo-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: photo-service
spec:
  ports:
  - protocol: TCP
    port: 5001
  selector:
    app: photo-service
