apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favorites-service
  template:
    metadata:
      labels:
        app: favorites-service
    spec:
      containers:
      - name: favorites-service
        image: favorites-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: favorites-service
spec:
  ports:
  - protocol: TCP
    port: 5001
  selector:
    app: favorites-service
